version: '3.8'

services:
  web:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app

  celery_worker:
    build: .
    command: bash -c "cd /app && sleep 10 && celery -A celery_worker worker -Q notifications --loglevel=info"
    working_dir: /app
    depends_on:
      - rabbitmq
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "15672:15672"
    env_file:
      - .env

volumes:
  postgres_data:
