version: "3.8"

services:
  web:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - API_HOST=57.129.71.50
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env

  celery_worker:
    build: .
    command: celery -A workers.celery_worker worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis

volumes:
  postgres_data:
