"""Add campaign_id to notifications table

Revision ID: 467c1f281f95
Revises: e22dd0590cea
Create Date: 2025-04-14 19:46:48.880955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467c1f281f95'
down_revision: Union[str, None] = 'e22dd0590cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('campaign_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'campaign_id')
    # ### end Alembic commands ###
