"""Add variant_id to notifications table

Revision ID: 5165584f706e
Revises: d6ab612fe325
Create Date: 2025-04-14 19:50:28.621566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5165584f706e'
down_revision: Union[str, None] = 'd6ab612fe325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('variant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'test_variants', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'variant_id')
    # ### end Alembic commands ###
