"""user role improved

Revision ID: 788c0e495df2
Revises: 4ab831d3abbd
Create Date: 2025-04-14 20:42:58.478082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788c0e495df2'
down_revision: Union[str, None] = '4ab831d3abbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_role_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_role_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='user_role_pkey')
    )
    # ### end Alembic commands ###
