"""Add user_id to notifications table

Revision ID: be4d2ad135c9
Revises: 5165584f706e
Create Date: 2025-04-14 19:51:53.454917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4d2ad135c9'
down_revision: Union[str, None] = '5165584f706e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'user_id')
    # ### end Alembic commands ###
