"""Add campaign_id to analytics table

Revision ID: d6ab612fe325
Revises: 467c1f281f95
Create Date: 2025-04-14 19:48:06.403840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ab612fe325'
down_revision: Union[str, None] = '467c1f281f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('campaign_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'analytics', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analytics', type_='foreignkey')
    op.drop_column('analytics', 'campaign_id')
    # ### end Alembic commands ###
