"""Add user_id to analytics table

Revision ID: fc04c7bba563
Revises: be4d2ad135c9
Create Date: 2025-04-14 19:53:09.254218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc04c7bba563'
down_revision: Union[str, None] = 'be4d2ad135c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'analytics', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analytics', type_='foreignkey')
    op.drop_column('analytics', 'user_id')
    # ### end Alembic commands ###
